version: '3.3'

services:
  api-dev:
    container_name: rest-api-dev
    restart: unless-stopped
    # tty: true
    build: 
      context: ./socket-server/socket
      dockerfile: Dockerfile.dev
    ports:
      - 3333:3333
    environment:
      - CONFIG_SERVICE=https://app-config-service-220618130713.azurewebsites.net
    networks:
      - devat

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./socket-server/socket/nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-dev
    networks:
      - devat

networks:
  devat: