# Stage 1: build
FROM node:16-alpine as build

WORKDIR /dist

ENV REACT_APP_CONFIG_SERVICE=http://travel-together-production.eastus2.cloudapp.azure.com/api
ENV REACT_APP_SOCKET_URL=http://travel-together-production.eastus2.cloudapp.azure.com

COPY . .

RUN npm i && npm run build

# Stage 2: prod
FROM nginx:1.21.5-alpine

COPY --from=build /dist/build /usr/share/nginx/html

COPY --from=build /dist/nginx.conf /etc/nginx/conf.d/default.conf

CMD [ "nginx", "-g", "daemon off;" ]