FROM openjdk:8u111-jdk-alpine
VOLUME /tmp
ADD target/config-service-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-Dspring.data.mongodb.uri=mongodb://mongo:27017/travel-together","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
